apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: minimal-fake-metrics-server-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-autoscaler
    app.kubernetes.io/part-of: pvc-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: minimal-fake-metrics-server
  namespace: monitoring