configMapGenerator:
- name: minimal-fake-metrics-config
  files:
  - nginx.conf
  - metrics.txt
  - pod_bytes_low_1Gi.txt
  - pod_bytes_high_1Gi.txt
  - pod_bytes_low_2Gi.txt
  - pod_bytes_high_2Gi.txt
  - pod_bytes_low_3Gi.txt
  - pod_bytes_high_3Gi.txt
  - pod_inode_low_1Gi.txt
  - pod_inode_high_1Gi.txt
  - pod_inode_low_2Gi.txt
  - pod_inode_high_2Gi.txt
  - pod_inode_low_3Gi.txt
  - pod_inode_high_3Gi.txt

resources:
- metrics-test-pod-with-pvc.yaml
- fake.yaml
- monitor.yaml
