configMapGenerator:
- name: minimal-fake-metrics-config
  files:
  - nginx.conf
  - metrics.txt

resources:
- metrics-test-pod-with-pvc.yaml
- fake_service_account.yaml
- fake_role.yaml
- fake_role_binding.yaml
- fake.yaml
- monitor.yaml
