configMapGenerator:
- name: minimal-fake-metrics-config
  files:
  - nginx.conf
  - metrics.txt
  - dummy_stage1.txt
  - dummy_stage2.txt
  - dummy_stage3.txt

resources:
- metrics-test-pod-with-pvc.yaml
- fake.yaml
- monitor.yaml
