configMapGenerator:
- name: minimal-fake-metrics-config
  files:
  - nginx.conf
  - metrics.txt
  - dummy_stage1.txt
  - dummy_stage2.txt
  - dummy_stage3.txt
  - dummy_stage4.txt
  - dummy_stage5.txt
  - dummy_stage6.txt
  - dummy_stage7.txt
  - dummy_stage8.txt
  - dummy_stage9.txt
  - dummy_stage10.txt
  - dummy_stage11.txt
  - dummy_stage12.txt

resources:
- metrics-test-pod-with-pvc.yaml
- fake.yaml
- monitor.yaml
